name: Inject template into README
on:
  schedule:
    - cron: "0 8 * * 2,5"
  # cron notation: https://en.wikipedia.org/wiki/Cron#CRON_expression
    # "(second) [minute] [hour] [day-of-month] [month] [day-of-week] (year)"
    # * = every
    # [x],[y] = list of values (ex. "1,3" = 1 and 3)
    # [x]-[y] = range of values between and including x and y (ex. "1-3" = 1 and 2 and 3)
    # [x]/[n] = starting with value x, every nth value (ex. "*/6" = 0, 6, 12, ...; "3/2" = 3, 5, 7, ...)
  # non-standard cron operators:
    # [x]#[n] = [day-of-week] = the nth occurrence of the xth day of the week (ex. "1#3" = the 3rd Monday of the month)
    # [x]W = [day-of-month] = weekday (MON-FRI) nearest the given day (ex. "9W" = weekday nearest the 9th day of the month)
    # ? = [day-of-month] or [day-of-week] = nil value, defer to behavior indicated by other field
    # L = [day-of-month] = last day of month (ex. "L" = Jan 31 and Apr 30),
    #     [day-of-week] = last X day of the week, of the month (ex. "6L" = last Friday of the month)
    # LW = [day-of-month] = last weekday of the month (ex. "LW" = Fri, Oct 29 and Tues, Nov 30)

jobs:
  inject_dynamic_content_into_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Inject template into README
      uses: actions/setup-node@v2
      with:
        node-version: 14.18.0
        yarn: true
    - run: yarn
    - run: node .

    - name: Commit changes
      run: |
        git pull
        git add .
        git config --global user.name "Travis Martin"
        git config --global user.email "travisemerymartin@gmail.com"
        git commit -m "[Automated] Update README"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
